### ISSUE TITLE
DX12 version of HITMAN crashes on launch

### ISSUE THREAD

**Issue by SwooshyCueb** [Kaldaien/SpecialK#1]
I can't give you logs right this second, but HITMAN's DX12 build crashes right after spawning a window. Tested with the dll renamed and put in the folder with HITMAN.exe and with the AppInit functionality.

As well, the launcher spawns a process and just sits there, never presenting a window, with SuperK loaded via AppInit. Using the compatibility keybind to disable SpecialK seems to get it working, though

**Comment by Kaldaien** [comment]
It may be related to the Steam overlay, that's the problem with most D3D12 games and my mod :-\ Disabling the overlay sometimes isn't enough and you have to physically move GameOverlayRenderer{64}.dll out of the Steam directory temporarily to rule out Steam as the cause.

**Comment by Kaldaien** [comment]
Assuming this is closed for now, I will know for sure in a week or so when I re-visit D3D12 support :)
