### ISSUE TITLE
FFXV Crashing upon launch

### ISSUE THREAD

**Issue by chr1831** [Kaldaien/SpecialK#10]
Good evening,

When attempting to launch FFXV after installing special k I receive the MGS crash sound, and the game quits.

Hardware:
OS: Windows 10 PRO latest non insider build
CPU: Ryzen 5 1600
GPU: RX570
Controller: DS4 w/ [DS4 Windows](https://github.com/Ryochan7/DS4Windows)

Logs:
[crash.log](https://github.com/Kaldaien/SpecialK/files/1795701/crash.log)
[dxgi.log](https://github.com/Kaldaien/SpecialK/files/1795702/dxgi.log)
[dxgi_budget.log](https://github.com/Kaldaien/SpecialK/files/1795703/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/SpecialK/files/1795704/game_output.log)
[modules.log](https://github.com/Kaldaien/SpecialK/files/1795705/modules.log)
[steam_api.log](https://github.com/Kaldaien/SpecialK/files/1795706/steam_api.log)

**Comment by Idearum** [comment]
Yo,

Please note that Kaldaien doesn't really monitor the Issues section here on GitHub. You're better of requesting help over on the thread for FFXV to ensure the highest possible chance of support:
http://steamcommunity.com/app/637650/discussions/0/1697167168518535998/

Anyway, back to your logs. The way your modules.log cuts of in the middle of everything (there's a whole section missing at the bottom of it) makes me think you're using a third-party tool that is incompatible with Special K. The usual suspect for this kind of symptom (partially missing modules.log file) is FRAPS, but other third-party stuff like MSI Nahimic, Dxtory, MSI Afterburner, RivaTuner Statistics Server (RTSS), Razer Chroma and similar applications, etc can all result in a similar issue. Please check and see if you have any of those running in the background.

**Comment by chr1831** [comment]
@Idearum Thanks for the heads up. I'll make sure I post over there with a link to the ticket.

The only thing I was using was the steam FPS overlay to monitor the performance. I disabled that, and the game still crashes. Looks like the modules now gets further along, and I can see Special K listed.

[dxgi.log](https://github.com/Kaldaien/SpecialK/files/1797726/dxgi.log)
[dxgi_budget.log](https://github.com/Kaldaien/SpecialK/files/1797727/dxgi_budget.log)
[game_output.log](https://github.com/Kaldaien/SpecialK/files/1797728/game_output.log)
[modules.log](https://github.com/Kaldaien/SpecialK/files/1797729/modules.log)
[steam_api.log](https://github.com/Kaldaien/SpecialK/files/1797730/steam_api.log)
[crash.log](https://github.com/Kaldaien/SpecialK/files/1797731/crash.log)

**Comment by chr1831** [comment]
Here's the logs from 9.8.3

[dxgi_budget.log](https://github.com/Kaldaien/SpecialK/files/1797976/dxgi_budget.log)

[modules.log](https://github.com/Kaldaien/SpecialK/files/1797977/modules.log)
[steam_api.log](https://github.com/Kaldaien/SpecialK/files/1797978/steam_api.log)
[crash.log](https://github.com/Kaldaien/SpecialK/files/1797979/crash.log)
[dxgi.log](https://github.com/Kaldaien/SpecialK/files/1797980/dxgi.log)

**Comment by chr1831** [comment]
Issue resolved in 0.9.9 most likely with the inclusion of d3dcompiler 43.
