### ISSUE TITLE
How to get rid of FPS display on Ys Seven?

### ISSUE THREAD

**Issue by edale2** [Kaldaien/SpecialK#12]
I'm playing the GoG version of Ys Seven (v1.0.0.7), with the mods described here: https://www.neogaf.com/threads/ys-seven-pc-ot-trails-in-the-flash-guard.1425401/page-3#post-248235818
Although I used Ys_Test7, rather than the Ys_Test4 linked in that post.

Everything seems to be working great, except now I have Special K's FPS monitor in the upper left corner of the screen... How do I get rid of that while keeping the injected textures? I've never used Special K for anything before this.

**Comment by Keith94** [comment]
Try pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd>.

**Comment by edale2** [comment]
Worked perfectly! Thanks!
Any other shortcut keys I should know?

**Comment by Keith94** [comment]
Ctrl + Shift + Backspace is a useful one.

Take a look at keybindings section here:
https://steamcommunity.com/sharedfiles/filedetails/?id=933337066

**Comment by edale2** [comment]
Thanks again.

Closing issue.
