### ISSUE TITLE
Temperature shown in °F, no option to set to °C.

### ISSUE THREAD

**Issue by Geemer** [Kaldaien/SpecialK#20]
The OSD shows the GPU temperature in °F with no option to switch to °C.

**Comment by Geemer** [comment]
Stumbled upon the option hidden away in an ini far away from the game directory (Documents\My Mods\SpecialK\Global\osd.ini).

Please consider adding it to the GUI settings that show up with ctrl+shift+backspace, though.

**Comment by 13xforever** [comment]
Specifically, it's in "%userprofile%\Documents\..." in case you moved your Documents folder and can't find the settings.

**Comment by Kaldaien** [comment]
It's in the config menu now, and the latest version of Special K and projects that use it have moved away from the %USERPROFILE% convention.

It's a real shame that Microsoft does not have a %DOCUMENTS% environment variable, I really wanted to give users an invariant path that they could copy-paste without having to accommodate for user account name, drive letters, etc. but Microsoft went and screwed that al up :)

Documents are now stored in the Shell Known Directory, which is unrelated to any environment variable. It's harder to locate, but at least it's in the proper location now :)

**Comment by Geemer** [comment]
Thanks a bunch for your efforts!
