### ISSUE TITLE
Global Injector does not work (0.8.1)

### ISSUE THREAD

**Issue by BlackArmsGeneral** [Kaldaien/SpecialK#26]
Installing the Global Injector from SKIM64 creates a My Mods folder and drops SpecialK32.dll and SpecialK64.dll in the SpecialK folder, but clicking the Start Injecting button does nothing.

I tried the inject.bat file, but it throws up this error: http://i.imgur.com/y1SAKQX.png

Uninject.bat throws up the same error.

This is a fresh install of windows, so I might be missing some runtime, please let me know if I've overlooked something.

> Operating System
> 	Windows 10 Home 64-bit
> CPU
> 	AMD FX-6100
> 	Zambezi 32nm Technology
> RAM
> 	12.0GB Dual-Channel DDR3 @ 666MHz (9-9-9-24)
> Motherboard
> 	ASUSTeK Computer INC. M5A88-M (AM3R2)
> Graphics
> 	LD-2657DF (1920x1080@60Hz)
> 	2048MB ATI AMD Radeon HD 7800 Series (XFX Pine Group)
> Storage
> 	298GB Western Digital WDC WD3200AAJS-57VWA2 ATA Device (SATA)
> 	232GB Seagate ST3250310AS ATA Device (SATA)
> 	931GB Western Digital WDC WD10EZEX-00BN5A0 ATA Device (SATA)
> 	931GB Western Digital WDC WD10EARS-00Y5B1 ATA Device (SATA)
> Optical Drives
> 	ASUS DRW-24F1ST a ATA Device
> Audio
> 	AMD High Definition Audio Device

EDIT: I forgot to point out that FAR works perfectly when installed with SKIM64. It seems it's only the Global Injector that is not working.

**Comment by Idearum** [comment]
I would assume you might be missing some files:
* https://www.microsoft.com/en-us/download/details.aspx?id=53587
* https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by BlackArmsGeneral** [comment]
Installed both. Same errors.

**Comment by Kaldaien** [comment]
Don't install the global injector with SKIM for now. Grab the pre-packaged release files and then place them in Documents\My Mods\SpecialK

The install manager needs a lot of code re-writing to support the new injection method and auto-update. You can use it to start/stop injection after you've manually installed those DLLs.

**Comment by BlackArmsGeneral** [comment]
Well that "fixed" it. But now every game just crashes as long as I leave it injected. Guess that's why we're not at 1.0 yet huh?

I'll close this now, thanks.
