### ISSUE TITLE
Crash on Inject

### ISSUE THREAD

**Issue by JYNxYoshii** [Kaldaien/SpecialK#44]
Straight to it. I've downloaded SK releases 10.2.1, 10.3, and 8.66; in every single case, the installer crashes when I click Install. No error, no freeze, just an immediate crash. I've tried this on 7 and 8.1, regular and Administrative launch, all to the same result. From what little I could glean from existing issues, this could be because I have multiple Steam library folders. Since I don't expect a fix, is there a guide somewhere for manual installation?

**Comment by Idearum** [comment]
Extract the archives to Documents\My Mods\SpecialK.

If done correctly the start global injection option should be available.

**Comment by JYNxYoshii** [comment]
Cool, thanks.
