### ISSUE TITLE
Horizon Zero Dawn

### ISSUE THREAD

**Issue by Kirbyarm** [Kaldaien/SpecialK#47]
We desperately need our hero Kaldaien to add Depth of Field / Bloom / Sunrays option to this new Steam PC release! My apologies if this is the wrong place for that kind of thing.

**Comment by Idearum** [comment]
Horizon: Zero Dawn is a D3D12 game, meaning there's very little Special K can do in that game.

The few things it can do is mostly related to improving frame pacing.

There's an official thread on that game over on the Special K forums: https://discourse.differentk.fyi/t/horizon-zero-dawn/224

**Comment by Kirbyarm** [comment]
Thank you very much for this. I'll keep a lookout there!
