### ISSUE TITLE
Sometimes, attempting to close a game while the updater is still open causes both to crash

### ISSUE THREAD

**Issue by SwooshyCueb** [Kaldaien/SpecialK#5]
Sometimes, but not always, closing a game while the updater is still open will cause the updater to crash while the game stays open, then the game crashes. Both of these crashes trigger Windows' builtin crash handling, sometimes twice.

**Comment by Kaldaien** [comment]
I think this has been solved. The update dialog used to delay parts of SpecialK that the game kind of needed (e.g. Direct3D stuff), most games would casually wait until the dialog was dismissed but others rendered in a separate thread while my dialog was running.
