### ISSUE TITLE
Same suggestion (new)

### ISSUE THREAD

**Issue by NeilTohno** [Kaldaien/SpecialK#8]
Thanks,
This mod worked very well, there are four suggestion for this mod:
1. Plesae don't add the update mode in SpecialK.
Because my pc have Windows Firewall Control and net doesn't work well,
When I  launch the Game, it crashes.

2. Plesae reduce time of the "welcome screen", in the mod.
When the launch the game, it will play the Opening movie, long time of the "welcome screen",
means I need time to paly the the Opening movie until it completed.

3. RAM optimization.
Ues more RAM for games.
Because my pc is "low-end computer", I found same game's ram  useage is very low.

4. create a Version don't contain CEGUI
Same game can't show CEGUI well, and I just use old Version.

**Comment by Idearum** [comment]
1. Use the auto-update feature of SKIM. Right click on the tray icon -> Manage -> Special K -> Check Version.

2. This can be configured in the control panel.

3. Eh? If you mean why the VRAM counter of Special K is lower than other tools then that's because SK reports *actual used VRAM* while other tools reports system-wide or something else. Basically SK's is more accurate.

4. Disable CEGUI in the control panel.

**Comment by NeilTohno** [comment]
>  This can be configured in the control panel.

Could you provide a default_d3d9.ini that Include comments for me, thanks.

**Comment by Idearum** [comment]
It isn't a setting defined in the local config file. You configure it the most easily through the in-game GUI:
![ys8_2018-01-27_19-35-15](https://user-images.githubusercontent.com/10578344/35475133-5252548a-0399-11e8-9e3c-f7c20ee5b4d4.png)

The setting is stored globally, and will be applied in all games.

**Comment by NeilTohno** [comment]
> The setting is stored globally, and will be applied in all games.
Get it,thanks.

**Comment by NeilTohno** [comment]
> Use the auto-update feature of SKIM. Right click on the tray icon -> Manage -> Special K -> Check Version.
你好，Plesae tell me how to disable the auto-update completely.
When I launch the Game, it crashe crashe and crashe .
